app.py
from flask import Flask
from routes.academia import academias_route
from routes.sobre import sobre_route
from routes.home import home_route
from routes.profile import profile_route
from routes.login import login_route


app = Flask(__name__)
app.register_blueprint(home_route)
app.register_blueprint(academias_route)
app.register_blueprint(sobre_route)
app.register_blueprint(profile_route)

if __name__ == '__main__':
    app.run(debug=True)

routes/academia.py
from flask import Blueprint, render_template

academias_route = Blueprint('academias', __name__)

@academias_route.route('/lista_academias')
def academias():
    return render_template('listar_academias.html')

@academias_route.route('/<int:academia_id>', methods=["GET"])
def detalhes_academia(academia_id):
    return render_template('academia.html')

routes/home.py
from flask import Blueprint, render_template

home_route = Blueprint('home', __name__)

@home_route.route('/')
def home():
    return render_template('index.html')

routes/login.py
from flask import Blueprint, render_template

login_route = Blueprint('login', __name__)

@login_route.route('/login', methods=['GET', 'POST'])
def login(username, password):
    return render_template('login.html')

@login_route.route('/signin', methods=['POST'])
def signin():
    return render_template('signin.html')

routes/profile.py
from flask import Blueprint, render_template

profile_route = Blueprint('profile', __name__)

@profile_route.route('/profile')
def profile():
    return render_template('profile.html')

@profile_route.route('/profile', methods=['POST'])
def editar_profile():
    pass

routes/sobre.py
from flask import Blueprint, render_template

sobre_route = Blueprint('sobre', __name__)

@sobre_route.route('/sobre')
def sobre():
    return render_template('sobre.html')

templates/academia.html
{% extends 'base.html' %}


{%  block head %}{% endblock %}
{%  block body %}
<h1>Academia</h1>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/modern-normalize.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}">
    {%  block head %}{% endblock %}
    <title>Document</title>
</head>
<body>
    <script type="module" src="{{ url_for('static', filename='js/bootstrap.bundle.min.js')}}"></script>
    <header class="d-flex justify-content-center py-3"> 
        <ul class="nav nav-pills"> 
            <li class="nav-item"><a href="{{ url_for('home.home') }}" class="nav-link active" aria-current="page">Home</a></li> 
            <li class="nav-item"><a href="{{ url_for('academias.academias') }}" class="nav-link">Academias</a></li>
            <li class="nav-item"><a href="{{ url_for('sobre.sobre') }}" class="nav-link">Sobre</a></li> 
        </ul> 
    </header> 
    
    {%  block body %}
    
    {% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}


{%  block head %}{% endblock %}
{%  block body %}
<div class="px-4 pt-5 my-5 text-center border-bottom"> <h1 class="display-4 fw-bold text-body-emphasis">Centered screenshot</h1> <div class="col-lg-6 mx-auto"> <p class="lead mb-4">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit, featuring Sass variables and mixins, responsive grid system, extensive prebuilt components, and powerful JavaScript plugins.</p> <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5"> <button type="button" class="btn btn-primary btn-lg px-4 me-sm-3">Primary button</button> <button type="button" class="btn btn-outline-secondary btn-lg px-4">Secondary</button> </div> </div> <div class="overflow-hidden" style="max-height: 30vh;"> </div> </div>
{% endblock %}

templates/listar_academias.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/modern-normalize.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}">
    <title>Document</title>
</head>
<body>
    <h1>teste</h1>
    <script type="module" src="{{ url_for('static', filename='js/bootstrap.bundle.min.js')}}"></script>
</body>
</html>

templates/login.html
{% extends 'base.html' %}
{%  block head %}
{% endblock %}
{%  block body %}
{% endblock %}

templates/signin.html
{% extends 'base.html' %}
{%  block head %}
{% endblock %}
{%  block body %}
{% endblock %}

templates/sobre.html
{% extends 'base.html' %}


{%  block head %}{% endblock %}
{%  block body %}
<main class="flex-shrink-0"> <div class="container"> <h1 class="mt-5">Sticky footer</h1> <p class="lead">Pin a footer to the bottom of the viewport in desktop browsers with this custom HTML and CSS.</p> <p>Use <a href="/docs/5.3/examples/sticky-footer-navbar/">the sticky footer with a fixed navbar</a> if need be, too.</p> </div> </main>
{% endblock %}